### PR TITLE
Fix/Unify event creation design for public and private events

### LINKED ISSUE #325: unify the design between the private and public event creation screens.
Currently, the Create Private Event and Create Public Event screens feel like two completely different parts of the application.

Visual Inconsistency: The private event form lacks the modern styling of the public form (e.g., it is missing the banner card and uses different padding/spacing).

Navigation Disconnect: When a user creates a public event, they are taken to the new event's details. However, when creating a private event, the app simply navigates "Back" to the previous list. This forces the user to search for the event they just created to verify the details.

**Solution :** We need to add consistent look and navigation for both public and private event creation screens

### PR DESCRIPTION
**Pull request by haaissa**
fixes #325 

## What?
Unified the post-creation navigation flow and standardized the `CreatePrivateEventScreen` design to match the `CreatePublicEventScreen`.

## Why?
To ensure a consistent user experience across event types, where users are redirected to the Event View after saving, and to resolve UI inconsistencies between the private and public event creation forms.

## How?
* **Navigation:** Implemented `MapsToEvent` `SharedFlow` in both ViewModels to redirect users to the specific Event View after a successful save, replacing the previous behavior of simply navigating back.
* **UI Redesign:** Refactored `CreatePrivateEventScreen` to mirror the layout of `CreatePublicEventScreen`, specifically adopting the floating save button animation, the card-based banner section, and standardized form field spacing.

## Before
image

## After
image

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/ui/eventcreation/CommonEventFields.kt [hunk 1]
```diff
@@ -0,0 +1,245 @@
...
+import com.github.se.studentconnect.R
+import com.github.se.studentconnect.model.location.Location
+import com.github.se.studentconnect.ui.components.PicturePickerCard
+import com.github.se.studentconnect.ui.components.PicturePickerStyle
+import com.github.se.studentconnect.ui.utils.DialogNotImplemented
+import java.time.LocalDate
+import java.time.LocalTime
+
+@Composable
+fun EventTitleAndDescriptionFields(
```
Comment (83759) [inline app/src/main/java/com/github/se/studentconnect/ui/eventcreation/CommonEventFields.kt]: missing documentation (also all other public composables in this file)

File: app/src/main/java/com/github/se/studentconnect/ui/eventcreation/CreatePrivateEventViewModel.kt [hunk 2]
```diff
@@ -1,210 +1,83 @@
...
-
-  fun updateBannerImageUri(newUri: Uri) {
-    _uiState.value = uiState.value.copy(bannerImageUri = newUri, shouldRemoveBanner = false)
-  }
-
-  fun removeBannerImage() {
-    _uiState.value =
-        uiState.value.copy(bannerImageUri = null, bannerImagePath = null, shouldRemoveBanner = true)
-  }
+class CreatePrivateEventViewModel :
```
Comment (83759) [inline app/src/main/java/com/github/se/studentconnect/ui/eventcreation/CreatePrivateEventViewModel.kt]: nice! just add documentation

**Review by 83759 — APPROVED** [review]
good job ur pr ready now
