### PR TITLE
fix(activities): cancel event refresh on tab selection

### LINKED ISSUE #304: Fix: activities tab loads incorrect content when switching tabs quickly
**Issue:** Fix: activities tab loads incorrect content when switching tabs quickly

Resolve the issue where switching tabs rapidly causes the activities tab to display incorrect content. Ensure proper state separation and correct loading behavior.

### PR DESCRIPTION
**Pull request by haaissa**
fixes #304 

## What?
Fixes a race condition in the "Activities" tab where rapid navigation caused data from previous tabs to appear in the current view.

## Why?
Network requests triggered by previous tab selections were completing after the user had already switched tabs, causing the UI to update with the wrong content.

## How?
Refactored the data fetching logic to use a `refreshJob`. Now, when a new tab is selected, any ongoing fetch operation is immediately cancelled to ensure only the relevant data is displayed.

## Before

https://github.com/user-attachments/assets/51392b18-0f5b-49eb-be1a-c31b5c178d2a

## After

https://github.com/user-attachments/assets/b0cac225-c666-42ad-9402-27a9ffa250c5

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt [hunk 1]
```diff
@@ -82,113 +85,126 @@ class ActivitiesViewModel(
...
+                  val joinedEventIds = userRepository.getJoinedEvents(userUid)
+
+                  val allVisibleEvents =
+                      try {
+                        eventRepository.getAllVisibleEvents()
+                      } catch (e: Exception) {
+                        _uiState.update {
+                          it.copy(
+                              errorMessage =
+                                  "Failed to load events: ${e.message ?: "Unknown error"}")
```
Comment (83759) [inline app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt]: this should be in strings.xml

File: app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt [hunk 2]
```diff
@@ -82,113 +85,126 @@ class ActivitiesViewModel(
...
+                  val joinedEvents = userRepository.getJoinedEvents(userUid)
+
+                  val allVisibleEvents =
+                      try {
+                        eventRepository.getAllVisibleEvents()
+                      } catch (e: Exception) {
+                        _uiState.update {
+                          it.copy(
+                              errorMessage =
+                                  "Failed to load events: ${e.message ?: "Unknown error"}")
```
Comment (83759) [inline app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt]: this in strings.xml as well

**Review by 83759 — CHANGES_REQUESTED** [review]
Nice PR, just put strings in strings.xml if it is you who created them

Line coverage is above 80%, nice

**Comment by haaissa** [comment]
We can merge I think 

image

**Review by 83759 — APPROVED** [review]
thanks for your changes, you put everything in strings.xml
