### PR TITLE
Fix/sign up buttons alignment

### LINKED ISSUE #102: fix in sign up screens
Buttons like `continue`, `skip`, `left arrow` are not at the same place durimg navigation (design is not consistent across screens).

### PR DESCRIPTION
**Pull request by haaissa**
This PR fixes #102 

> **AI Assistance:** Parts of the code refactoring and associated documentation for this PR were assisted by AI tools. 

## What

This PR introduces a set of reusable, standardized **Jetpack Compose UI components** and refactors the entire **sign-up flow** to use them.

This work standardizes the look and feel of text, buttons, titles, and icons across all related screens, including:
* `BasicInfoScreen`
* `AddPictureScreen`
* `DescriptionScreen`
* `ExperiencesScreen`
* `NationalityScreen`

## Why

The sign-up flow previously used inconsistent styling and components across its different screens. This led to a disjointed user experience and increased code duplication.

This change was needed to **create a consistent look and feel** for the user and **improve code maintainability** by centralizing UI logic into reusable components.

## How

1.  A new set of **reusable Jetpack Compose components** was introduced to serve as the single source of truth for the sign-up UI in the fiel `SignUpCommonComponents`.
2.  Each screen in the sign-up flow (e.g., `AddPictureScreen.kt`, `BasicInfoScreen.kt`) was then **refactored** to remove custom, local implementations and replace them with calls to the new common components.
3.  The `google-services.json` file was updated.

> There is one test in `GettingStartedScreenTest` that fails and have been removed in this PR. Another PR (#107) is fixing this issue

### Old
https://github.com/user-attachments/assets/a4f5641a-2e0a-416a-a85d-6001901a8059

### New
https://github.com/user-attachments/assets/01d5af44-faa6-422e-b986-0fce2d282711

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/ui/screen/signup/AddPictureScreen.kt [hunk 1]
```diff
@@ -78,42 +73,30 @@ fun AddPictureScreen(
...
+          SignUpSkipButton(
               onClick = {
                 viewModel.setProfilePictureUri(DEFAULT_PLACEHOLDER)
                 profileUri = DEFAULT_PLACEHOLDER
                 onSkip()
               })
         }
 
-        Spacer(Modifier.height(16.dp))
+        SignUpMediumSpacer()
```
Comment (83759) [inline app/src/main/java/com/github/se/studentconnect/ui/screen/signup/AddPictureScreen.kt]: nice modularization!

File: app/src/main/java/com/github/se/studentconnect/ui/screen/signup/SignUpCommonComponents.kt [hunk 2]
```diff
@@ -0,0 +1,256 @@
...
+import androidx.compose.ui.text.style.TextOverflow
+import androidx.compose.ui.unit.dp
+
+/**
+ * Common constants for all sign-up screens to ensure visual consistency.
+ *
+ * These values define the standard spacing, sizing, and styling used throughout the sign-up flow to
+ * create a unified user experience.
+ */
+object SignUpScreenConstants {
```
Comment (83759) [inline app/src/main/java/com/github/se/studentconnect/ui/screen/signup/SignUpCommonComponents.kt]: good idea to put all constants in a common class!

**Review by 83759 — CHANGES_REQUESTED** [review]
Nice code! You nicely modularized everything and moved common components to a utilities class, keeping the behavior the same. Since the behavior is the same, no logic changes are required. Just make sure to keep the test which was fixed in #107 so that it remains in the main branch.

**Comment by haaissa** [comment]
Thank you for your review. I’ve made the requested changes, and the CI now passes (no more code duplication).
I believe we’re ready to merge, unless you have any further comments.
