### PR TITLE
Fix/private events logic

### LINKED ISSUE #152: fix private events
Private events presented some bugs : 
- The private events were visible in homePage 
- Since events were accecible by everyone clicking on it crashes (only in the case were you're the owner)
- PPrivate evnts were considered as public ones (even in UI there is no difference)

### PR DESCRIPTION
**Pull request by haaissa**
> [!important]
> This PR contains +1K lines of test; code changes are not too much.## What

## What 

This PR introduces the logic for handling private events by implementing access control and updating the views to reflect event visibility (public vs. private). I added tests and others were also cleaned up.

## Why

Previously, the application did not clearly distinguish between public and private events. Private events were not correctly hidden on the homepage, and the logic allowing an owner to see their own events or a guest to see them (only after accepting) was not implemented.

## How

**Access Control (Repository):** 
- Implemented `getallvisibleEvents` in EventRepositoryFirestore to filter events based on user rights.
**ViewModels:**
- `HomeViewModel` now only displays public events.
- `ActivitiesViewModel` now includes private events belonging to the user.
**Refined Logic:** 
- A guest user will only see the event in the "upcoming" list after accepting the invitation.
**UI:**
- Added icons on ActivitiesScreen to differentiate between public and private events.
- Added an "Invite friends" icon (full logic is not yet implemented).
**Tests:** 
- Removed invalid tests and added new ones to cover the new visibility rules.
- Added some tests that helped me find bugs
> AI was used to write tests

Fixes #152

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/model/event/EventRepositoryFirestore.kt [hunk 1]
```diff
@@ -39,31 +39,27 @@ class EventRepositoryFirestore(private val db: FirebaseFirestore) : EventReposit
...
 
-  private fun privateEventFromDocumentSnapshot(documentSnapshot: DocumentSnapshot): Event.Private {
-    val uid = documentSnapshot.id
-    val ownerId = checkNotNull(documentSnapshot.getString("ownerId"))
-    val title = checkNotNull(documentSnapshot.getString("title"))
+  /**
+   * Extracts common event fields from a DocumentSnapshot. This helper function eliminates code
+   * duplication between private and public event parsing.
+   */
+  private fun extractCommonEventFields(documentSnapshot: DocumentSnapshot): CommonEventFields {
```
Comment (rita-naimi) [inline app/src/main/java/com/github/se/studentconnect/model/event/EventRepositoryFirestore.kt]: good job! it reduces duplication and improves maintainability

File: app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt [hunk 2]
```diff
@@ -94,7 +94,23 @@ class ActivitiesViewModel(
...
+                  } catch (e: Exception) {
+                    _uiState.update {
+                      it.copy(
+                          errorMessage = "Failed to load events: ${e.message ?: "Unknown error"}")
+                    }
+                    emptyList()
+                  }
+
+              val ownedEvents = allVisibleEvents.filter { it.ownerId == userUid }
+              val allEventIds = (joinedEvents + ownedEvents.map { it.uid }).distinct()
```
Comment (rita-naimi) [inline app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt]: Small performance concern: You're fetching all visible events, then filtering for owned ones, but then calling `getEvent()` again for each event ID. Since `allVisibleEvents` already has the full event objects, you're fetching the same events twice; use the events from `allVisibleEvents` directly for owned events, and only fetch events from `joinedEvents` that aren't already in `allVisibleEvents` to avoid unnecessary calls.

**Review by rita-naimi — CHANGES_REQUESTED** [review]
Great work on this PR. The refactoring to handle private events is well-structured, and the code is clean and maintainable. Congrats on the line coverage above 90%! It shows solid testing.

I only suggested minor performance improvements (using `event.ownerId` instead of re-reading from the document, and avoiding redundant event fetches in ActivitiesViewModel). The logic and implementation look solid overall.
Good job.

File: app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt (hunk 2 above)
Comment (haaissa) [reply app/src/main/java/com/github/se/studentconnect/ui/screen/activities/ActivitiesViewModel.kt]: done
