### PR TITLE
Fix Edit Profile navigation after saving a modification

### LINKED ISSUE #164: Fix navigation to Edit Profile screen after saving a change
**Issue:** Editing profile fields does not automatically navigate back to the profile screen after a successful save.

- After saving changes in any edit profile screen, users stay on the edit page.
- A success message appears, but it is redundant since changes are visible on the profile screen.
- Expected behavior: automatically navigate back to the profile screen on successful save.
- Affected screens: name, birthday, activities, nationality.

### PR DESCRIPTION
**Pull request by rita-naimi**
## What
This PR adds automatic navigation back to the profile screen immediately after successfully saving profile edits.  
The changes apply to all profile editing screens (name, birthday, activities, and nationality).  
Success message notifications have been removed to provide a cleaner, more streamlined user experience.

## Why
Previously, after saving profile changes, users would see a success message and remain on the edit screen, requiring manual navigation back to the profile page.  
This created unnecessary friction in the user flow. Users expect to be returned to the profile screen after completing an edit operation, similar to standard mobile app patterns.  
The success messages were also redundant since the user can immediately see their changes reflected on the profile screen after navigation.

## How
- **Navigation Implementation:** Modified all edit profile screens (`EditNameScreen`, `EditBirthdayScreen`, `EditActivitiesScreen`, `EditNationalityScreen`) to automatically navigate back to the profile screen when a successful save operation is detected via `LaunchedEffect`.  
- **State Management:** Updated the `LaunchedEffect` handlers to call `onNavigateBack()` immediately when the success state is detected, before resetting the view model state to avoid cancelling the navigation effect.  
- **UX Improvements:** Removed success message snackbar notifications from all edit screens while preserving error message display for validation feedback.  
- **Code Cleanup:** Removed unused `kotlinx.coroutines.delay` imports and unused `coroutineScope` variable that were no longer needed after removing delays.  
- The navigation callbacks are already properly wired in `MainActivity.kt` using `navController.popBackStack()`, so no changes were needed there.

Fixes #164

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/ui/screen/profile/edit/EditBirthdayScreen.kt [hunk 1]
```diff
@@ -64,11 +63,10 @@ fun EditBirthdayScreen(
   LaunchedEffect(uiState) {
     when (val state = uiState) {
       is EditBirthdayViewModel.UiState.Success -> {
-        snackbarHostState.showSnackbar(state.message)
-        viewModel.resetState()
-        // Navigate back after successful save
-        delay(500)
+        // Navigate back immediately after successful save
         onNavigateBack()
+        // Reset state after navigation to avoid cancelling LaunchedEffect
```
Comment (TristanBour) [inline app/src/main/java/com/github/se/studentconnect/ui/screen/profile/edit/EditBirthdayScreen.kt]: Nice catch!

**Review by TristanBour — APPROVED** [review]
Perfect!
