### PR TITLE
Fix event location length in Event Card and Search Bar

### LINKED ISSUE #157: Fix location length in event card
**Issue:** Event cards display full Nominatim addresses, making location text overly long and hard to read.

- Event cards currently show the complete `display_name` returned by Nominatim.
- These addresses can be extremely verbose (multiple comma-separated components).
- This hurts readability and clutters the event list and search results.
- We need a shorter, human-friendly version of the address.
- Affected areas: event list cards and search result cards.

### PR DESCRIPTION
**Pull request by rita-naimi**
## What
Event cards now display shortened, human-readable addresses instead of the full Nominatim `display_name`.  
Added a utility function to format addresses and applied it to event cards in both the event list and search results.

## Why
Event cards were showing the complete Nominatim `display_name`, which can be very long (e.g., "Rue de la Gare, Quartier du Centre, Lausanne, District de Lausanne, Vaud, 1000, Switzerland").  
This makes the location text unnecessarily verbose and harder to read.

## How
- Created `formatShortAddress()` in `AddressUtils.kt` that:  
  - Extracts the first 3 comma-separated parts (road, neighbourhood/suburb, city/town/village)  
  - Falls back to the first 2 parts if needed  
  - Truncates to 50 characters with ellipsis  

- Updated `EventCard` in `ListOfEvents.kt` to use the formatted address with `maxLines = 1` and `TextOverflow.Ellipsis`  

- Applied the same formatting to event cards in `Search.kt` for consistency

Fixes #157

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/ui/utils/AddressUtils.kt [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+  val shortAddress =
+      if (addressParts.size >= 2) {
+        addressParts.joinToString(", ")
+      } else {
+        parts.take(2).joinToString(", ")
+      }
+
+  return if (shortAddress.length > 50) {
+    shortAddress.take(47) + "..."
```
Comment (haaissa) [inline app/src/main/java/com/github/se/studentconnect/ui/utils/AddressUtils.kt]: Logic looks great, Nice Job! However, you have used a lot of magic numbers try to move them to constants

Comment (rita-naimi) [reply app/src/main/java/com/github/se/studentconnect/ui/utils/AddressUtils.kt]: Thanks for the feedback, you're absolutely right. I've replaced all the magic numbers with named constants defined at the top of the file

File: app/src/main/java/com/github/se/studentconnect/ui/utils/ListOfEvents.kt [hunk 2]
```diff
@@ -195,9 +195,11 @@ fun EventCard(
                 modifier = Modifier.testTag("event_card_title_${event.uid}"))
             Spacer(modifier = Modifier.height(4.dp))
             Text(
-                text = event.location?.name ?: "Location not specified",
+                text = formatShortAddress(event.location?.name),
                 style = MaterialTheme.typography.bodyMedium,
-                color = MaterialTheme.colorScheme.onSurfaceVariant)
+                color = MaterialTheme.colorScheme.onSurfaceVariant,
+                maxLines = 1,
```
[the remark this answers is not in the document]
Comment (rita-naimi) [reply app/src/main/java/com/github/se/studentconnect/ui/utils/ListOfEvents.kt]: Good catch hahah. It's now referred to as `MAX_LINES_FOR_ADDRESS_TEXT`.

**Review by haaissa — APPROVED** [review]
Thanks for your changes! PR ready to merge!
