### PR TITLE
Fix/exit the location dropdown popup

### LINKED ISSUE #315: Fix (organization signup flow): allow users to exit the location dropdown popup
**Issue:** Fix (organization signup flow): allow users to exit the location dropdown popup

Ensure that users can properly close or exit the location dropdown popup during the organization signup flow. Add a clear dismissal action so the user can return to the form without being blocked.

### PR DESCRIPTION
**Pull request by haaissa**
## What?
Fixed the layout and dismissal behavior of the location dropdown in the organization sign-up screen.

## Why?
To ensure the dropdown visually aligns with the input field, supports scrolling for long lists (preventing screen overflow), and can be easily dismissed by the user.

## How?
* Used `Modifier.onSizeChanged` to synchronize the dropdown width with the text field.
* Applied `Modifier.heightIn` to limit the height (approx. 6 items), forcing scrolling for longer lists.
* Leveraged standard `DropdownMenu` behavior to allow clicking outside to exit.

fixes #315

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/ui/screen/signup/organization/OrganizationProfileSetupScreen.kt [hunk 1]
```diff
@@ -214,76 +216,74 @@ private fun LocationDropdownField(
...
+                  }
+            }
+        DropdownMenu(
+            expanded = expanded,
+            onDismissRequest = { onExpandedChange(false) },
+            modifier =
+                Modifier.background(MaterialTheme.colorScheme.surface)
+                    .width(dropdownWidth)
+                    .heightIn(max = DropdownMaxHeight)) {
+              options.forEach { option ->
```
Comment (83759) [inline app/src/main/java/com/github/se/studentconnect/ui/screen/signup/organization/OrganizationProfileSetupScreen.kt]: perfect code, everything is in constants, nice

**Review by 83759 — APPROVED** [review]
nice fix, everything is fine (line coverage >80%)

File: app/src/main/java/com/github/se/studentconnect/ui/screen/signup/organization/OrganizationProfileSetupScreen.kt (hunk 1 above)
Comment (haaissa) [reply app/src/main/java/com/github/se/studentconnect/ui/screen/signup/organization/OrganizationProfileSetupScreen.kt]: yep we learn from our errors to improve
