### PR TITLE
Fix/use username instead of user

### LINKED ISSUE #358: replace userID by username
**Problem:**
In the `userCard` and the, `notifications` which were both implemented before the username was added, we are using the user ID—the random ID generated by Firebase.
Image

Image

### PR DESCRIPTION
**Pull request by haaissa**
fixes #358 

## What?

Displays the user handle prefixed with `@` in notifications (e.g. `@habibi`) instead of the first/last name or an unformatted value.

## Why?
- The `@username` handle is unique and more easily recognizable in notifications.
- Ensures consistency with product expectations (the user explicitly requested the `@` prefix).
- Improves notification readability and avoids ambiguities related to first/last names.

## How?
- Formatting is handled on the ViewModel / notification mapping side:
  - The `username` field is retrieved and prefixed with `@`.
- The fields used in the `Notification` model (`fromUserName`, `eventOwnerName`, `invitedByName`) are populated with this formatted handle when the notification is created/emitted.
- The UI (e.g. `HomeScreen.kt`) directly displays these fields; the notification rendering function (`getUsernameAndTime`) now uses the pre-formatted value and properly handles null or empty cases.
- Tests and visual previews have been updated to verify the “after” appearance (notifications displaying `@username`).

## Before
Image

Image
 
## After

image

image

### CODE REVIEW

File: app/src/main/java/com/github/se/studentconnect/model/notification/Notification.kt [hunk 1]
```diff
@@ -215,6 +218,7 @@ sealed class Notification {
                 userId = map["userId"] as? String ?: "",
                 eventId = map["eventId"] as? String ?: "",
                 eventTitle = map["eventTitle"] as? String ?: "",
+                eventOwnerName = map["eventOwnerName"] as? String ?: "",
```
Comment (othmanehousni) [inline app/src/main/java/com/github/se/studentconnect/model/notification/Notification.kt]: consider a safe fallback like "unknown" instead of an empty string, to avoid blank usernames in the UI.

Comment (haaissa) [reply app/src/main/java/com/github/se/studentconnect/model/notification/Notification.kt]: there is always the username, so this should not be a problem.

**Review by HamzaZbr — APPROVED** [review]
Thanks for clarifying. 
It's fine for me !
LGTM
